name: "Build"
on:
  push:
    branches:
      - "4.x"
    tags:
      - v4*
  pull_request:
    branches:
      - "4.x"
    types: [opened, reopened, synchronize]

jobs:
  build: 
    name: Build All Packages
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/setup-node@v1
        with: 
          node-version: 14
      - uses: actions/checkout@v2
      - run: yarn

  lint:
    name: Lint
    needs: build
    runs-on: ubuntu-latest
    env:
      TEST: "build_and_lint"
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps: 
      - uses: actions/setup-node@v1
        with: 
          node-version: 14
      - uses: actions/checkout@v2
      - run: yarn lint

  unit:
    name: Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 14, 16 ]
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/checkout@v2
      - run: yarn
      - run: yarn test:unit

  integration:
    name: Integration
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [ 14, 16 ]
        backend: ['geth', 'ganache']
        mode: ['http', 'ws']
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      -   uses: actions/checkout@v2
      -   run: yarn
      -   run: yarn test:e2e:${{ matrix.backend }}:${{ matrix.mode }}
          shell: bash

  e2e:
    name: End-to-End
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [ 14, 16 ]
        browser: ['electron', 'chrome', 'firefox']
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      -   uses: actions/checkout@v2
      -   run: yarn
      -   run: test:e2e:browsers:${{ matrix.browser }}
          shell: bash
          